### ISSUE TITLE
Probably just confused

### ISSUE THREAD

**Issue by thunderc90** [kxbmap/configs#10]
Looking to use something like this config file (currently in application.conf): 

default {
  depth = 7
  prune = true
}

red-player {
  pType = Human
  depth = ${default.depth}
  prune = ${default.prune}
}

black-player {
  pType = Human
  depth = ${default.depth}
  prune = ${default.prune}
}

I'm trying to create two instances of this case class (defined in a PlayerSettings.scala file):

sealed trait ScalaPlayerType
case object Human extends ScalaPlayerType
case object Computer extends ScalaPlayerType

case class PlayerSetting(
                        pType: ScalaPlayerType,
                        depth: Int,
                        prune: Boolean
                           )

To retrieve the settings for red-player and black-player, but I'm running into a fairly obnoxious error..

(this is the code in my main method)

    val config = ConfigFactory.load()

    val redPlayer = config.get[PlayerSetting]("red-player")
    val blackPlayer = config.get[PlayerSetting]("black-player")

    println("Red Player: \n" + redPlayer)
    println("Black Player \n" + blackPlayer)

I'm not sure if I'm just doing something stupid, or if I really stumbled across a bug. Very new to scala in general, so it could really be something simple. 
Error Below:

Exception in thread "main" com.typesafe.config.ConfigException$BadValue: merge of system properties,application.conf @ file:/G:/Software%20Dev%20Stuff/workspace/ScalaConnectFour/target/scala-2.11/classes/application.conf: 1: Invalid value at 'black-player': null
	at com.github.kxbmap.configs.Configs$.com$github$kxbmap$configs$Configs$$get$body$2(Configs.scala:77)
	at com.github.kxbmap.configs.Configs$$anonfun$2.get(Configs.scala:72)
	at com.github.kxbmap.configs.syntax.package$ConfigOps$.get$extension(package.scala:29)
	at ConnectFourScala$.main(ConnectFour.scala:19)
	at ConnectFourScala.main(ConnectFour.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at ConnectFourScala$$anonfun$self$lzycompute$6$1.a$macro$14$lzycompute$1(ConnectFour.scala:19)
	at ConnectFourScala$$anonfun$self$lzycompute$6$1.a$macro$14$1(ConnectFour.scala:19)
	at ConnectFourScala$$anonfun$self$lzycompute$6$1.apply(ConnectFour.scala:19)
	at ConnectFourScala$$anonfun$self$lzycompute$6$1.apply(ConnectFour.scala:19)
	at com.github.kxbmap.configs.package$PipeOps$.$bar$greater$extension(package.scala:25)
	at com.github.kxbmap.configs.Configs$$anonfun$onPath$1.apply(Configs.scala:80)
	at com.github.kxbmap.configs.Configs$$anonfun$onPath$1.apply(Configs.scala:80)
	at com.github.kxbmap.configs.Configs$.com$github$kxbmap$configs$Configs$$get$body$2(Configs.scala:74)
	... 9 more

**Comment by thunderc90** [comment]
Oddly enough, it appears to work fine if I remove the second player... only works for the first player no matter what order i retrieve them in.

Can i not do two sepparate instances of the case classes or something?

**Comment by kxbmap** [comment]
Sorry for late reply.

I can't reproduce this problem. Your code works fine for me.

> Caused by: java.lang.NullPointerException
> at ... (ConnectFour.scala:19)

This line raises a NPE. It seems to be the cause.
